version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: crm-api-image
    container_name: crm-api
    ports:
      - '8000:8000'
    volumes:
      - ./api/:/usr/src/crm/api/
    tty: true
  web:
    build: ./web
    image: crm-web-image
    container_name: crm-web
    ports:
      - '8080:8080'
    volumes:
      - ./web/:/usr/src/crm/web/
    tty: true
    depends_on:
      - api
